# Site settings
title: Ray Bogman
domain: raybogman.com
description: Entrepeneur | Speaker | Trainer | Author | Host | Consultant
cover: assets/images/raybogman-1280.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "http://localhost" # the base hostname & protocol for your site
robots: INDEX,FOLLOW
email: hello@raybogman.com
fb_app_id: 560465084319172
paginate:	5 # The number of posts to show per page on your homepage

# Social
linkedin: raybogman
facebook: raybogman
instagram: raybogman
twitter: raybogman
github:  raybogman
prezi: raybogman

#Additional Pages
about: about
contact: contact
#privacy-policy: privacy-policy

permalink: /:title

# Google Analytics
analytics_id: UA-115396940-1

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
