/**
 * Markdown content negotiation at the edge (acceptmarkdown.com).
 *
 * GitHub Pages can't vary on Accept, so this Worker (route: raybogman.com/*)
 * does it: requests preferring text/markdown get the page's hand-authored
 * .md twin (generated by _plugins/ai_markdown.rb); everything else passes
 * through with `Vary: Accept` appended so caches key correctly.
 * Markdown requests for unknown paths get a markdown 404 with recovery links.
 */

// Parse Accept per RFC 9110: does the client prefer text/markdown over text/html?
function prefersMarkdown(accept) {
  if (!accept) return false;
  let md = null;
  let html = null;
  for (const part of accept.split(",")) {
    const params = part.trim().split(";").map((s) => s.trim());
    const type = params[0].toLowerCase();
    let q = 1;
    for (const p of params.slice(1)) {
      const [k, v] = p.split("=").map((s) => s && s.trim());
      if (k === "q") {
        const n = Number(v);
        if (!Number.isNaN(n)) q = Math.max(0, Math.min(1, n));
      }
    }
    // Specificity: exact > text/* > */*
    const spec = type === "*/*" ? 0 : type.endsWith("/*") ? 1 : 2;
    if (type === "text/markdown" && (!md || q > md.q)) md = { q, spec };
    if ((type === "text/html" || type === "text/*" || type === "*/*") &&
        (!html || q > html.q || (q === html.q && spec > html.spec))) html = { q, spec };
  }
  if (!md || md.q === 0) return false;
  if (!html) return true;
  return md.q > html.q || (md.q === html.q && md.spec >= html.spec);
}

const NOT_FOUND_MD = `# 404 — Page not found

This URL does not exist on raybogman.com.

Recover via:

- [Site index for agents](https://raybogman.com/llms.txt)
- [Full site as one Markdown document](https://raybogman.com/llms-full.txt)
- [Sitemap](https://raybogman.com/sitemap.xml)

Every HTML page has a Markdown twin at the same path with a \`.md\` suffix
(e.g. https://raybogman.com/about.md).
`;

function mdHeaders(extra = {}) {
  return {
    "content-type": "text/markdown; charset=utf-8",
    vary: "Accept",
    ...extra,
  };
}

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const path = url.pathname;
    // Only negotiate on HTML-ish paths (no file extension, or .html).
    const negotiable =
      (request.method === "GET" || request.method === "HEAD") &&
      (!/\.[a-z0-9]+$/i.test(path) || path.endsWith(".html") || path.endsWith("/"));

    if (negotiable && prefersMarkdown(request.headers.get("accept"))) {
      // Homepage has no .md twin; llms.txt is its markdown representation.
      const twin = path === "/" || path === "/index.html"
        ? "/llms.txt"
        : path.replace(/\/$/, "").replace(/\.html$/, "") + ".md";
      const res = await fetch(new URL(twin, url.origin), {
        cf: { cacheTtl: 300 },
        headers: { "user-agent": request.headers.get("user-agent") || "worker" },
      });
      const head = request.method === "HEAD";
      if (res.ok) {
        return new Response(head ? null : res.body, { status: 200, headers: mdHeaders() });
      }
      return new Response(head ? null : NOT_FOUND_MD, { status: 404, headers: mdHeaders() });
    }

    // Pass through; append Vary: Accept on HTML so caches store variants separately.
    const res = await fetch(request);
    const type = res.headers.get("content-type") || "";
    if (type.includes("text/html")) {
      const out = new Response(res.body, res);
      const vary = out.headers.get("vary");
      if (!vary || !/\baccept\b/i.test(vary.replace(/accept-\w+/gi, ""))) {
        out.headers.append("Vary", "Accept");
      }
      return out;
    }
    return res;
  },
};
